"""
Django settings for hulolo project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# 程式碼 5-2
import os

LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET")
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN")

# 以下先加上print跑啟動網站，看看是否有在指令中成功獲得環境變數
print(LINE_CHANNEL_SECRET, LINE_CHANNEL_ACCESS_TOKEN)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "這是一個重要的密鑰，每個專案皆不同，切勿公開至 GitHub 或其他平台！"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 留意此處應更換為實際的 Ngrok URL，而非以下的範例 URL
ALLOWED_HOSTS = ["127.0.0.1", "4b2f-114-45-OOO.ngrok-free.app"]

# 程式碼 10-3
# 特別留意網域調整成 PythonAnywhere's username，前幾行相同的變數 ALLOWED_HOSTS 將會被覆蓋
ALLOWED_HOSTS = ["hulolo.pythonanywhere.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 程式碼 6-6
    'import_export', # 幫助做資料輸入輸出成表格檔   
    'chatbot' # 這裡放新增的 APP 名稱

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hulolo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 圖 8-2
        "DIRS": ['static'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hulolo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 程式碼 10-2，一開始 setting.py 就有它了
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 程式碼 9-19
SENIOR_RICH_MENU_ID = os.getenv("SENIOR_RICH_MENU_ID")
DEFAULT_FIRST_PAGE_RICH_MENU_ID = os.getenv("DEFAULT_FIRST_PAGE_RICH_MENU_ID")
DEFAULT_SECOND_PAGE_RICH_MENU_ID = os.getenv("DEFAULT_SECOND_PAGE_RICH_MENU_ID")

# 程式碼 10-1
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')