# Generated by Django 5.2.15 on 2026-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("GEN", "通識課程"),
                            ("EDU", "教育學程"),
                            ("PSS", "大二體育"),
                            ("PJS", "大三四體育"),
                            ("LAN", "精進中英外文"),
                            ("MIL", "軍訓"),
                        ],
                        default="GEN",
                        max_length=3,
                        verbose_name="類型",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        help_text="以教務系統顯示的全名為主", max_length=20, verbose_name="課名"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        help_text="【合開】連【】也要記得輸進去哦！",
                        max_length=20,
                        verbose_name="老師/【合開】",
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        default="匿名",
                        help_text="不口以超過15字",
                        max_length=15,
                        verbose_name="投稿者",
                    ),
                ),
                ("feedback_content", models.TextField(verbose_name="內容")),
                (
                    "evaluation_semester",
                    models.CharField(default="114-1", max_length=5),
                ),
                (
                    "last_updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="上次修改日期"),
                ),
            ],
        ),
    ]
