# Generated by Django 5.2.15 on 2026-06-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=20, verbose_name="全稱")),
                ("alias", models.CharField(max_length=20, verbose_name="簡稱")),
            ],
        ),
    ]
