# Generated by Django 5.2.15 on 2026-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_coursealias"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        max_length=33, unique=True, verbose_name="User ID"
                    ),
                ),
                ("display_name", models.CharField(max_length=20, verbose_name="顯示名稱")),
                ("year", models.CharField(max_length=4, verbose_name="系級")),
                ("join_date", models.DateTimeField(auto_now=True, verbose_name="加入日期")),
            ],
        ),
    ]
